# coding:utf-8

- hosts: all
  sudo: yes

  tasks:

    - name: locale setting
      shell: 'cp -p  /usr/share/zoneinfo/Japan /etc/localtime'

    - name: upgrade all packages
      yum: name=* state=latest

    - name: install common
      yum: name=git disable_gpg_check=no state=installed

    ## TODO Jenkins add wheel group.
    ## TODO and http://qiita.com/gozuqi/items/6ebb2e6a4d49dfeb080f

    # Docker install

    - name: install docker
      yum: name=docker-io disable_gpg_check=no state=installed

    - name: start docker
      service: name=docker enabled=yes state=started

    # Jeknins install

    - name: yum jdk install for jenkins
      yum: name=java-1.8.0-openjdk-devel state=installed

    - name: jenkins repository instalkl
      shell: 'curl http://pkg.jenkins-ci.org/redhat/jenkins.repo > /etc/yum.repos.d/jenkins.repo'

    - name: jenkins key install
      shell: 'rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key'

    - name: jenkins install
      yum: name=jenkins state=installed

    - name: add docker group
      group: name=docker state=present

    - name: jenkins user add for docker
      user: name=jenkins groups=docker append=yes

    - name: jenkins service set
      service: name=jenkins enabled=yes state=started

    # install nginx

    - name: yum nginx install
      yum: name=nginx state=installed disable_gpg_check=no

    - name: ngix setting file copy
      copy:
        src: ./resources/nginx_conf.d/basic.conf
        dest: /etc/nginx/conf.d/basic.conf

    - name: nginx service set
      service: name=nginx enabled=yes state=started
